"use client";

// import "../../envConfig.ts";
import React, { useEffect } from "react";
// import "./envConfig.ts";
import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";

const inter = Inter({ subsets: ["latin"] });

import { NextUIProvider } from "@nextui-org/react";
import Header from "@/components/Header";
import Footer from "@/components/footer/Footer";
import useMainInformation from "@/hooks/main-information/useMainInformation";
import usePages from "@/hooks/usePages/usePages";
// import useMainInformation from "@/hooks/main-information/useMainInformation";
// import { zusPages } from "@/zustand/pages/zusPages";
// import useMainInformation from "@/hooks/main-information/useMainInformation";
// import usePages from "@/hooks/usePages/usePages";
// import usePages from "@/hooks/usePages/usePages";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// ("use client");

// useMainInformation();
export default function RootLayout({ children }) {
  useMainInformation();
  usePages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          {/* <div className="flex justify-center">
            <div
              className="fixed  w-full opacity-100 bg-black h-auto z-50 mx-auto text-white"
              style={{ maxWidth: 1000 }}
            >
              <i></i>
              <p></p>
              <div className="bg-red-700">
                <p>hola</p>
                <input type="text" className="bg-red-300" />
              </div>
              <div>
                <p></p>
                <input type="text" />
              </div>
              <div>
                <p></p>
                <input type="text" />
              </div>
              <div>
                <p></p>
                <input type="text" />
              </div>
              <div>
                <p></p>
                <input type="text" />
              </div>
              <div>
                <p></p>
                <input type="text" />
              </div>
            </div>
          </div> */}
          {/* <div className="fixed z-50">
            <div
              className="text-center absolute w-full h-full"
              style={{ paddingLeft: "6px", paddingRight: "6px" }}
            >
              <div
                className="opacity-100 bg-black-"
                style={{
                  maxWidth: "1000px",
                  border: "2px solid hsla(0,0%,100%,.25)",
                }}
              >
                <div className="p-10 bg-black ">hola</div>
              </div>
            </div>
          </div> */}
          {/* <div
            className="fixed bg-red-500 min-h-screen w-full z-50 mx-auto"
            style={{ maxWidth: 1000 }}
          ></div> */}
          <Header />
          <main className={`pt-20 ${!true && "fixed bg-black opacity-80"}`}>
            {children}
          </main>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
